CACTUS/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static  
# from dashboard.views import custom_404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls')),
    path('payment/', include('payment.urls')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
# handler404 = custom_404

accounts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
app_name = 'accounts'
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('signup',views.signup, name='signup'),
    path('signin',views.signin, name='signin'),
    path('signinwithotp',views.signinotp, name='signinotp'),
    path('confirmlogin',views.otp, name='otp'),
    path('logout',views.log_out, name='logout'),
    path('forgotpassword',views.forgotpassword, name='forgotpassword'),
    
    path('verifyemail',views.verifyemail, name='verifyemail'),
    path('profile',views.profile, name='profile'),
    path('profile/add_address',views.add_address, name='add_address'),
    path('profile/edit_address/<int:id>',views.edit_address, name='edit_address'),
    path('profile/delete_address/<int:id>',views.delete_address, name='delete_address'),
    path('profile/update_password',views.update_password, name='update_password'),
    path('myprofile',views.my_profile, name='my_profile'),
    path('editprofile',views.editprofile, name='editprofile'),
    path('addressbook',views.addressbook, name='addressbook'),
    path('updateaddress',views.updateaddress, name='updateaddress'),
    path('myorders',views.myorders, name='myorders'),
    path('manage_order/<int:id>',views.manage_order, name='manage_order'),
    path('returnedorders',views.returnedorders, name='returnedorders'),
    path('wallet',views.wallet,name="mywallet"),
    
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('reset_password/<uidb64>/<token>/',views.reset_password,name='reset_password'),
    path('resetpassword/', views.resetpassword, name='resetpassword'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from .views import custom_404_view

app_name = 'store'

urlpatterns = [
    path('search/', views.search_view, name='search'),
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('allproducts/', views.allproducts, name='allproducts'),
    path('product/<str:slug>/<str:size>', views.product_detail, name='product_detail'),
    # path('<slug:category_slug>',views.shop,name ="product_by_category"),
    path('tag/<str:tag_name>',views.product_by_tags,name ="product_by_tags"),
    path('featured/<int:id>',views.classifiedproducts, name ="classifiedproducts"),
    path('profile',views.profile,name='profile'),
    path('cart/',views.cart,name="cart"),
    path('add_cart/<int:product_id>/<int:quantity>/',views.add_cart,name="add_cart"),
    path('remove_cart/<int:product_id>',views.remove_cart,name="remove_cart"),
    path('delete_cart/<int:product_id>',views.delete_cart,name="delete_cart"),
    path('checkout_manager/', views.checkout_manager, name='checkout_manager'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment_with_existing_address', views.payment_with_existing_address, name='payment_with_existing_address'),
    path('payment_with_new_address/', views.payment_with_new_address, name='payment_with_new_address'),
    path('payment/',views.payment,name = 'payment'),
    path('add_wishlist/<int:product_id>/',views.add_wishlist,name="add_wishlist"),
    path('check_stock',views.check_quantity,name="check_quantity"),
    path('get_added',views.get_added,name="get_added"),
    path('update_cart_quantity/',views.update_cart_quantity,name="update_cart_quantity"),
    path('decrease_cart_quantity/',views.decrease_cart_quantity,name="decrease_cart_quantity"),
    path('decrease_cart_quantity_os/',views.decrease_cart_quantity_os,name="decrease_cart_quantity_os"),
    path('check_quantity',views.check_quantity_cart,name="check_quantity_cart"),
    path('quantity_check',views.quantity_check,name="quantity_check"),
    path('apply_coupon',views.apply_coupon,name="apply_coupon"),
   
    
    
    path('checkout_signin/', views.checkout_signin, name='checkout_signin'),
    path('checkout_signup/', views.checkout_signup, name='checkout_signup'),
    path('checkout_signinotp/', views.checkout_signinotp, name='checkout_signinotp'),
    path('checkout_signinotp_verification/', views.checkout_signinotp_verification, name='checkout_signinotp_verification'),
]
handler404 = custom_404_view

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User_Accounts,AddressBook
from django.core.exceptions import ValidationError
import re
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


def validate_phone_number(value):
    # Define a regular expression pattern to match phone numbers with country code
    pattern = r'^\+\d{1,3}\d{9,10}$'
    if not re.match(pattern, value):
        raise ValidationError(
            'Please enter a phone number with country code, e.g. +91xxxxxxxxxx')


class CustomerRegisterForm(UserCreationForm):
    phone = forms.CharField(max_length=20, required=True,
                            help_text='Phone number', validators=[validate_phone_number])
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(required=False)
    STATUS_CHOICES = (
    ('active', 'Active'),
    ('suspended', 'Suspended'),
    ('blocked', 'Blocked'),
)

    status = forms.ChoiceField(choices=STATUS_CHOICES, label='Status', required=False, initial='active')


    class Meta:
        model = User_Accounts
        fields = ['email', 'phone', 'username', 'password1']
        widget = {
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your phone number',
                'maxlength': '10',
                'minlength': '10',
            }),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),

        }


class Signin_Form(forms.Form):
    login_cred = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class Otp_Form(forms.Form):
    otp = forms.CharField()
    
    

class AddressBookForm(forms.ModelForm):
    class Meta:
        model = AddressBook
        fields = ['first_name', 'last_name', 'phone', 'address_line_1', 'address_line_2', 'city', 'state', 'country', 'pincode', 'default']
    

accounts/views.py
from datetime import timedelta, timezone
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect

from .models import User_Accounts,AddressBook,Profile,Country,Cart,State,Wallet,Transaction,CartItem
from . forms import CustomerRegisterForm, Signin_Form , Otp_Form ,AddressBookForm
from django.contrib.auth import get_user_model
from django.contrib import messages,auth
from .manager import AccountsManager
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.hashers import check_password
from django.utils import timezone
import random
from django.contrib.auth import login as auth_login
from . import verify
from .otp import verify_otp
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password
from orders.models import Order,OrderProduct,Payment
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
import requests
from store.views import _cart_id
from store.views import catcom
# from .helpers import delete_expired_otp
# Create your views here.

account_manager = AccountsManager()

def is_superuser(user):
    return user.is_superuser

def signup(request):
    if request.method == 'POST':
        signupform = CustomerRegisterForm(request.POST)
        if signupform.is_valid():
            user = signupform.save()
            wallet = Wallet.objects.create(user=user, balance=100)
            Transaction.objects.create(user=user, amount=100, transaction_type='credit', description='Signup bonus')

            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exist = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exist:
                    cart_items = CartItem.objects.filter(cart=cart)
                    for item in cart_items:
                        item.user = user
                        item.cart = None
                        item.save()
            except Cart.DoesNotExist:
                pass
            return redirect('accounts:signin')
        else:
            for field_name, errors in signupform.errors.items():
                for error in errors:
                    messages.error(request, f"{field_name}: {error}")
    form = CustomerRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})

def signin(request):
    if request.method == 'POST':
        loginform = Signin_Form(request.POST)
        if loginform.is_valid():
            login_cred = loginform.cleaned_data['login_cred']
            password = loginform.cleaned_data['password']
            user = account_manager.authenticate(request, email=login_cred, phone=login_cred, username=login_cred, password=password)

            if user is not None:
                if not user.account_status =='active':
                    messages.error(request, 'Invalid login credentials')
                    return render(request, 'accounts/signin.html', {'form': loginform})
                    
                auth_login(request, user)

                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                    is_cart_item_exist = CartItem.objects.filter(cart=cart).exists()

                    if is_cart_item_exist:
                        cart_items = CartItem.objects.filter(cart=cart)

                        for item in cart_items:
                            item_in_user_cart = CartItem.objects.filter(user=user, product=item.product).exists()

                            if item_in_user_cart:
                                product = CartItem.objects.get(user=user, product=item.product)
                                product.quantity = item.quantity
                                item.delete()
                                product.save()
                            else:
                                new_cart_item = CartItem(user=user, quantity=item.quantity, product=item.product)
                                new_cart_item.save()
                except Cart.DoesNotExist:
                    pass
                if request.user.is_superuser:
                    return redirect("dashboard:dashboard")
                else:
                    return redirect("store:home")
            else:
                messages.error(request, 'Invalid login credentials')
                return render(request, 'accounts/signin.html', {'form': loginform})
        else:
            # Form is not valid; display form errors
            for field_name, errors in loginform.errors.items():
                for error in errors:
                    messages.error(request, f"{field_name}: {error}")
            return render(request, 'accounts/signin.html', {'form': loginform})
    
    loginform = Signin_Form()

    return render(request, 'accounts/signin.html', {'form': loginform})

def signinotp(request):
    if request.method == 'POST':
        login_cred = request.POST.get('login_cred')
        user = account_manager.getuser(
                request, email=login_cred, phone=login_cred, username=login_cred)
        if user is not None:
            request.session['email']=user.email
            verify.send(user.phone)
            otp_form = Otp_Form()
            return render(request, 'accounts/two_factorauth.html', {'form': otp_form , 'user' : user})          
        else:
            messages.error(request, 'Invalid login credentials')
            return HttpResponse('Invalid login credentials')
    return render(request, 'accounts/signinotp.html')

def otp(request):
    if request.method == 'POST':
        form = Otp_Form(request.POST)
        if form.is_valid():
            UserModel = get_user_model()
            code = form.cleaned_data['otp']
            user = UserModel.objects.get(email=request.session.get('email'))
            print(user.email)
            
            if verify.check(user.phone, code):
                messages.success(request, "OTP verified")
                auth.login(request, user)
                try:
                    cart = Cart.objects.get(cart_id= _cart_id(request))
                    is_cart_item_exist = CartItem.objects.filter(cart = cart).exists()
                    if is_cart_item_exist:
                        cart_items = CartItem.objects.filter(cart=cart)
                        for item in cart_items:
                            item_in_user_cart = CartItem.objects.filter(user = user,product = item.product).exists()
                            if item_in_user_cart:
                                product = CartItem.objects.get(user = user,product = item.product)
                                product.quantity = item.quantity
                                item.delete()
                                product.save()
                            else:
                                new_cart_item = CartItem(user=user, quantity=item.quantity, product=item.product)
                                new_cart_item.save()
                except:
                    pass
                if request.user.is_superuser:
                    return redirect("dashboard:dashboard")
                else:
                    return redirect("store:home")
            else:

                error_msg = "Invalid OTP. Please try again later."
                messages.error(request, error_msg)
        else:
            messages.error(request, "Invalid OTP form submission. Please try again.")
    else:
        form = Otp_Form()
        
    return render(request, 'accounts/two_factorauth.html', {'form': form})



def  verifyemail(request):
    return render(request, 'accounts/verifyemail.html')


def log_out(request):
    logout(request)
    return redirect('store:home')
def profile(request):
    current_user = request.user
    if current_user.is_authenticated:
        user = User_Accounts.objects.get(username = current_user.username)
        country = Country.objects.all()
        states = State.objects.all()
        addressform = AddressBookForm()
        orders = Order.objects.filter(user = request.user).exclude(status="New").order_by('-created_at')
        context = {
            'user' : user, 
            'states' : states,
            'country' : country,
            'addressform' : addressform, 
            'orders' : orders,   
        }
        context.update(catcom(request))
        try:
            if Profile.objects.filter(user = user).exists:
                profile = Profile.objects.get(user = user)
                context['profile'] = profile
        except:
            pass
        
        try:
            if AddressBook.objects.filter(user = user).exists:
                address = AddressBook.objects.filter(user = user)
                context['address'] = address
        except:
            pass
        try:
            if AddressBook.objects.filter(user = user , default = True).exists:
                d_address = AddressBook.objects.get(user = user ,default = True)
                context['d_address'] = d_address
        except:
            pass
        
      
        return render(request, 'accounts/profile1.html',context)
    
    
    return redirect('accounts:signin')



def edit_address(request,id):
    address = get_object_or_404(AddressBook, id=id)
    if request.method == 'POST':
        form = AddressBookForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
            context = {}

templates/accounts/addressbook.html
{% extends 'products/base.html' %}
{% load static %}

{% block main %}


    <!--====== Google Font ======-->
  <!-- Custom Google Fonts-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500;600&family=Roboto:wght@300;400;700&display=auto"
    rel="stylesheet">

    <!--====== Vendor Css ======-->
    <link rel="stylesheet" href="{% static 'profile/vendor.css' %}">

    <!--====== Utility-Spacing ======-->
    <link rel="stylesheet" href="{% static 'profile/utility.css' %}">

    <!--====== App ======-->
    <link rel="stylesheet" href="{% static 'profile/app.css' %}">

    <!--====== Main App ======-->
    <body class="config">
    <!--====== App Content ======-->
    <div class="app-content">

        <!--====== Section 1 ======-->
        <div class="u-s-p-y-60">

            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="container">
                    <div class="breadcrumb">
                        <div class="breadcrumb__wrap">
                            <ul class="breadcrumb__list">
                                <li class="has-separator">

                                    <a href="index.html">Home</a></li>
                                <li class="is-marked">

                                    <a href="dash-address-book.html">My Account</a></li>
                            </ul>
                        </div>
                        <button class="logout-button btn btn--e-brand-b-2">Logout</button>
                              
                        <style>
                                .logout-button {
                                margin-left: auto;
                              }           
                        </style> 
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section 1 ======-->


        <!--====== Section 2 ======-->
        <div class="u-s-p-b-60">

            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="dash">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-3 col-md-12">

                                <!--====== Dashboard Features ======-->
                                <div class="dash__box dash__box--bg-white dash__box--shadow u-s-m-b-30">
                                    <div class="dash__pad-1">

                                        <span class="dash__text u-s-m-b-16">Hello, John Doe</span>
                                        <ul class="dash__f-list">
                                            <li>

                                                <a href="{% url 'accounts:profile' %}">Manage My Account</a></li>
                                            <li>

                                                <a href="{% url 'accounts:my_profile' %}">My Profile</a></li>
                                            <li>

                                                <a class="dash-active" href="{% url 'accounts:addressbook' %}">Address Book</a></li>
                                            <li>

                                                <a href="{% url 'accounts:mywallet' %}">Wallet</a></li>
                                            <li>

                                                <a href="{% url 'accounts:myorders' %}">My Orders</a></li>
                                            <li>

                                                <a href="dash-payment-option.html">My Payment Options</a></li>
                                            <li>

                                                <a href="{% url 'accounts:returnedorders' %}">My Returns & Cancellations</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="dash__box dash__box--bg-white dash__box--shadow dash__box--w">
                                    <div class="dash__pad-1">
                                        <ul class="dash__w-list">
                                            <li>
                                                <div class="dash__w-wrap">

                                                    <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>

                                                    <span class="dash__w-text">4</span>

                                                    <span class="dash__w-name">Orders Placed</span></div>
                                            </li>
                                            <li>
                                                <div class="dash__w-wrap">

                                                    <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>

                                                    <span class="dash__w-text">0</span>

                                                    <span class="dash__w-name">Cancel Orders</span></div>
                                            </li>
                                            <li>
                                                <div class="dash__w-wrap">

                                                    <span class="dash__w-icon dash__w-icon-style-3"><i class="far fa-heart"></i></span>

                                                    <span class="dash__w-text">0</span>

                                                    <span class="dash__w-name">Wishlist</span></div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!--====== End - Dashboard Features ======-->
                            </div>
                            <div class="col-lg-9 col-md-12">
                                <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white u-s-m-b-30">
                                    <div class="dash__pad-2">
                                        <div class="dash__address-header">
                                            <h1 class="dash__h1">Address Book</h1>
                                         
                                    </div>
                                </div>
                                <div class="dash__box dash__box--shadow dash__box--bg-white dash__box--radius u-s-m-b-30">
                                    <div class="dash__table-2-wrap gl-scroll">
                                        <table class="dash__table-2">
                                            {% if address %}
                                            <thead>
                                                <tr>
                                                    <th>Action</th>
                                                    <th>Full Name</th>
                                                    <th>Address</th>
                                                    <th>city</th>
                                                    <th>Phone Number</th>
                                                    <th>zipcode</th>
                                                    <th>Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                
                                                {% for add in address %}
                                                <tr>
                                                    <td>

                                                        <a class="address-book-edit btn--e-transparent-platinum-b-2" href="dash-address-edit.html">Edit</a>
                                                        <a class="address-book-edit btn--e-transparent-platinum-b-2" href="{% url 'accounts:delete_address' add.id %}">Delete</a>
                                                    </td>
                                                    <td>{{add.first_name}} {{add.last_name}}</td>
                                                    <td>{{add.address_line_1}},{{add.address_line_2}}</td>
                                                    <td>{{add.city}}</td>
                                                    <td>{{add.phone}}</td>
                                                    <td>{{add.pincode}}</td>

                                                    <td>
                                                    {% if add.default %}
                                                    default address{% endif %}
                                                    </td>
                                                </tr>
                                                {% endfor %}
                                               
                                            </tbody>
                                            {% else %}
                                            <tr></tr>
                                            <td>there is no address added</td>
                                            {% endif %}
                                        </table>
                                    </div>
                                </div>
                                <div>

                                    <a class="dash__custom-link btn--e-brand-b-2" href="{% url 'accounts:updateaddress' %}"><i class="fas fa-plus u-s-m-r-8"></i>

                                        <span>Add New Address</span></a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section Content ======-->
        </div>
        <!--====== End - Section 2 ======-->
    </div>
    <!--====== End - App Content ======-->
    <!--====== End - Main App ======-->


    <!--====== Google Analytics: change UA-XXXXX-Y to be your site's ID ======-->
    <script>
        window.ga = function() {
            ga.q.push(arguments)
        };
        ga.q = [];
        ga.l = +new Date;
        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview')
    </script>
    <script src="https://www.google-analytics.com/analytics.js" async defer></script>

    <!--====== Vendor Js ======-->
    <script src="js/vendor.js"></script>

    <!--====== jQuery Shopnav plugin ======-->
    <script src="js/jquery.shopnav.js"></script>

    <!--====== App ======-->
    <script src="js/app.js"></script>

    <!--====== Noscript ======-->
    <noscript>
        <div class="app-setting">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="app-setting__wrap">
                            <h1 class="app-setting__h1">JavaScript is disabled in your browser.</h1>

                            <span class="app-setting__text">Please enable JavaScript in your browser or upgrade to a JavaScript-capable browser.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </noscript>



</body>

{% endblock main %}

templates/accounts/resetmailcontant.html
{% autoescape off %}

 Hello  {{user.username}}

As requested, please click below link to reset password.
http://{{domain}}{% url 'accounts:reset_password' uidb64=uid token=token %}

If it is not you, please ignore this email.

Thank you,
TEAM Cactus

{% endautoescape %}